### ISSUE TITLE
CSS/Javascript - Parallax scrolling - Scrollmagic link movement blocks other image links

### ISSUE THREAD

**Issue by LepoutreA** [janpaepke/ScrollMagic#251]
OK so I posted this on stackoverflow and nobody was able to find an answer. Here is the link to the post. 

http://stackoverflow.com/questions/28786791/css-javascript-parallax-scrolling-scrollmagic-link-movement-blocks-other-ima

I would be incredibly grateful +will give credit on my website to anyone who like find a solution to this problem. I m a newb but I m ready to code a lot to make it work. 

---
__EDIT (copied from stackoverflow):__

Hello fellow programmers,
I am new at programming in HTML5/CSS/Javascript and I will try to make my question as clear as possible.

I've used scroll magic on my website to have the navigation links scroll to the side as you scroll down. Here is the [link to the page](http://ahundredhuevos.com/test_paintings.html). Nevertheless, I've realized that when I do so, I can no longer click on the images below when the nav links and my image elements (with link area on them) are at the same lateral level: the Scrollmagic link movement blocks other image links. I would like to be able to still click on both links throughout the whole parallax scrolling, even when the navigation links and the thumbnail link are at the same level.

I've attempted to: change the z value for both elements, change the .site-nav and page-nav sizes and spent many hours on it trying to edit bits and pieces to see if where the problem can be solved, but all to no avail. Here are parts of the css that I feel is where the answer belongs but I might be wrong.

CSS for parallaxed nav links:

```css
    .site-nav {
    display: block;
    position: fixed;
    width: 100;
    text-align: center;}
```

CSS for image thumbnail links (with link to HR images):

```css
    .page-nav {
    display: block;
    width: 100%;
    text-align: center;
    z-index: 10;
    margin-top: 300px;
}
```

So if this sound like an easy answer for you, this would really help me out greatly. Hopefully my post is relevant and makes sense! Let me know if anything needs clarification.
