### ISSUE TITLE
position: fixed is added to pin div

### ISSUE THREAD

**Issue by BevCyc** [janpaepke/ScrollMagic#94]
How can I prevent  a style of position:fixed from being added to my pin container?  If I add !important to position: relative in .slide it stays relative but then there's extra padding above and below the slide.  Also why does `TweenMax.fromTo("#slide1head", 1, {backgroundPosition: "-1440px center"}, {backgroundPosition: "center center", ease: Linear.easeNone}` move from right to left?

Here's what I have:

``` html
<script type="text/javascript">
$(document).ready(function(){

    // init the controller
    var controller = new ScrollMagic({
        vertical: true,
        globalSceneOptions: {
            triggerHook: "onLeave"
        }
    });

    // slide 1 background
    var s1tween1 = new TimelineMax ()
        .add([
            /*TweenMax.to("#bg1", 1, {backgroundPosition: "center bottom", ease: Linear.easeNone})*/
            TweenMax.fromTo("#bg1", 1, {backgroundPosition: "center top", ease: Linear.easeNone}, {backgroundPosition: "center bottom", ease: Linear.easeNone})
        ]);

    var s1scene1 = new ScrollScene({
        triggerElement: "#slide1",
        duration: 5000,  
        offset: 0
    })
        .setTween(s1tween1)
        .setPin("#slide1")
        .addTo(controller);

    // slide 1 DU header left to right
    var s1tween2 = new TimelineMax ()
        .add([
            TweenMax.fromTo("#slide1head", 1, {backgroundPosition: "-1440px center"}, {backgroundPosition: "center center", ease: Linear.easeNone})
        ]);

    var s1scene2 = new ScrollScene({
        duration: 1000,  
        offset: 100
    })
        .setTween(s1tween2)
        .addTo(controller);

});
</script>

<div id="slide1">
    <div id="bg1">
            <div id="slide1head"></div>
    </div> <!-- /#bg1 -->
</div> <!-- /#slide1 -->
```

In the stylesheet style2.css I have: 

``` css
@charset "utf-8";
/* CSS Document */

body {
    background-color: #0FF;
}
body, html {
    height: 100%;
}
.slide {
    position: relative;
    max-width: 1440px;
    width: 100%;
    height: 100%;
    margin: 0 auto;
    padding: 0;
}
/* slide 1 */
#bg1 {
    background-image: url(../images/section1-starfield.jpg);
    background-repeat: no-repeat;
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    z-index: 1;
}
#slide1head {
    background-image: url(../images/slide1-header.png);
    background-position: -1440px center;
    background-repeat: no-repeat;
    width: 100%;
    height: 100%;
    z-index: 3;
}
```
